# Generated by Django 3.0.7 on 2020-06-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='json',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='whats_in_it',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='who_is_it_for',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
