# Generated by Django 3.0.7 on 2020-06-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_auto_20200625_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='whats_in_it',
        ),
        migrations.RemoveField(
            model_name='course',
            name='who_is_it_for',
        ),
        migrations.AlterField(
            model_name='course',
            name='json',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
